import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, MapPinned, Search, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "Find property professionals", description: "Find relevant local architects and builders for a better-prepared property project." };

export default function ProfessionalsPage() {
  return <><section className="page-hero pro-hero"><div className="shell split-heading"><div><p className="eyebrow">Professional network</p><h1>Find the right expertise for the actual project.</h1></div><p>PlotWorthy matches by location, project type and relevant experience — with clearer briefs and no hidden auction for your contact details.</p></div></section><section className="section"><div className="shell"><div className="feature-grid three"><article className="feature-card"><span><Search /></span><h3>Relevant matching</h3><p>Search by postcode coverage, discipline and specialism rather than a generic directory listing.</p></article><article className="feature-card"><span><BadgeCheck /></span><h3>Visible credentials</h3><p>Profiles are designed to show verification status, professional memberships, insurance and project evidence.</p></article><article className="feature-card"><span><ShieldCheck /></span><h3>You stay in control</h3><p>Your email is verified before an enquiry and is only shared when you choose to contact or request a response.</p></article></div></div></section><section className="section section-soft"><div className="shell marketplace-preview"><div><p className="eyebrow">Marketplace foundations</p><h2>What a useful professional profile should tell you.</h2><ul className="tick-list"><li><MapPinned /> Areas genuinely covered</li><li><BriefcaseBusiness /> Relevant project and consent experience</li><li><BadgeCheck /> Checks completed and last reviewed</li><li><ShieldCheck /> How enquiries and fees are handled</li></ul></div><div className="profile-sample"><div className="profile-top"><span>HA</span><div><p className="eyebrow">Example profile format</p><h3>Local architecture practice</h3><p>Architect · Greater Manchester</p></div></div><div className="tag-row"><span>HMOs</span><span>Conversions</span><span>Planning</span></div><p>Portfolio, verified details and enquiry availability would appear here. No practice is presented as vetted until checks are complete.</p></div></div></section><section className="cta-band"><div className="shell"><div><p className="eyebrow">Are you a professional?</p><h2>Help shape a higher-quality lead network.</h2></div><Link className="button button-light" href="/professionals/join">Apply to join <ArrowRight size={18} /></Link></div></section></>;
}
