import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Eye, Layers3, Scale, Users } from "lucide-react";

export const metadata: Metadata = { title: "About", description: "Why PlotWorthy is building a clearer first step for UK property projects." };

export default function AboutPage() {
  return <><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Why PlotWorthy</p><h1>Property potential deserves more than a confident guess.</h1><p>Important early evidence is spread across council portals, registers, maps and technical language. PlotWorthy is being built to make that first investigation clearer and more accountable.</p></div></section><section className="section"><div className="shell values-grid"><article><Eye /><h2>Show the source</h2><p>A useful claim should tell you where it came from, how current it is and whether the address match is reliable.</p></article><article><Layers3 /><h2>Separate the questions</h2><p>Planning, licensing, building regulations and commercial viability overlap, but they are not interchangeable.</p></article><article><Scale /><h2>Be honest about uncertainty</h2><p>We label what is unknown and identify the next check. PlotWorthy does not issue planning guarantees.</p></article><article><Users /><h2>Improve the handover</h2><p>A better evidence pack gives owners and professionals a more useful starting conversation.</p></article></div></section><section className="section section-soft"><div className="shell story-block"><div><p className="eyebrow">Built from practice</p><h2>A platform shaped by real feasibility questions.</h2></div><div><p>PlotWorthy began with a recurring problem: owners often spend money before the most important constraints, consent routes and evidence gaps are visible.</p><p>The aim is not to replace architects, planners, surveyors or councils. It is to help people reach the right professional with a clearer property record and a more realistic brief.</p><Link className="button" href="/check">Start a property check <ArrowRight size={18} /></Link></div></div></section></>;
}
