import type { Metadata } from "next";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy notice" };

export default function PrivacyPage() {
  return <Legal title="Privacy notice" updated="20 August 2026"><p>PlotWorthy is responsible for deciding how personal information submitted through this service is used. Contact us at <a href={`mailto:${site.email}`}>{site.email}</a> for privacy questions.</p><h2>Information we process</h2><p>Depending on the feature you use, this can include your email address, account identifiers, saved property addresses, project notes, professional profile information, enquiries, consent records and technical security logs.</p><h2>Why we process it</h2><p>We use information to provide requested property checks and accounts, secure the service, respond to enquiries, match an enquiry when you ask us to, administer professional profiles, meet legal obligations and improve the service. Our legal bases may include performance of a contract, legitimate interests, consent and legal obligation.</p><h2>Sharing</h2><p>We use service providers for hosting, authentication, data storage, email and monitoring. We do not sell your email address. Information is shared with a professional only when you choose to send or request an enquiry, or where the law requires disclosure.</p><h2>Retention and security</h2><p>We keep personal information only for as long as needed for the purpose, account administration, dispute handling and legal obligations. Retention periods vary by record type. We use access controls and encrypted service providers, but no online service can promise absolute security.</p><h2>Your rights</h2><p>UK data protection law may give you rights to access, correct, delete, restrict or object to processing, and to data portability. You can withdraw consent where consent is the basis. Contact us to make a request. You may also complain to the UK Information Commissioner’s Office.</p><h2>Cookies and changes</h2><p>Essential cookies may be used for security and sign-in. Optional analytics should only be enabled after an appropriate choice. We will update this notice when the service or processing materially changes.</p></Legal>;
}

function Legal({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) {
  return <article className="legal-page"><header><div className="shell narrow"><p className="eyebrow">Legal</p><h1>{title}</h1><p>Last updated {updated}</p></div></header><div className="shell legal-copy">{children}</div></article>;
}
