// Every UK postcode area, so admin can assign coverage for any city/region.
// Picking one pulls that area's real districts from the map data (with a
// range fallback if the fetch fails).

export type PostcodeArea = { code: string; name: string };

export const POSTCODE_AREAS: PostcodeArea[] = [
  { code: "AB", name: "Aberdeen" },
  { code: "AL", name: "St Albans" },
  { code: "B", name: "Birmingham" },
  { code: "BA", name: "Bath" },
  { code: "BB", name: "Blackburn" },
  { code: "BD", name: "Bradford" },
  { code: "BH", name: "Bournemouth" },
  { code: "BL", name: "Bolton" },
  { code: "BN", name: "Brighton" },
  { code: "BR", name: "Bromley" },
  { code: "BS", name: "Bristol" },
  { code: "BT", name: "Belfast" },
  { code: "CA", name: "Carlisle" },
  { code: "CB", name: "Cambridge" },
  { code: "CF", name: "Cardiff" },
  { code: "CH", name: "Chester" },
  { code: "CM", name: "Chelmsford" },
  { code: "CO", name: "Colchester" },
  { code: "CR", name: "Croydon" },
  { code: "CT", name: "Canterbury" },
  { code: "CV", name: "Coventry" },
  { code: "CW", name: "Crewe" },
  { code: "DA", name: "Dartford" },
  { code: "DD", name: "Dundee" },
  { code: "DE", name: "Derby" },
  { code: "DG", name: "Dumfries" },
  { code: "DH", name: "Durham" },
  { code: "DL", name: "Darlington" },
  { code: "DN", name: "Doncaster" },
  { code: "DT", name: "Dorchester" },
  { code: "DY", name: "Dudley" },
  { code: "E", name: "London E" },
  { code: "EC", name: "London EC" },
  { code: "EH", name: "Edinburgh" },
  { code: "EN", name: "Enfield" },
  { code: "EX", name: "Exeter" },
  { code: "FK", name: "Falkirk" },
  { code: "FY", name: "Blackpool" },
  { code: "G", name: "Glasgow" },
  { code: "GL", name: "Gloucester" },
  { code: "GU", name: "Guildford" },
  { code: "HA", name: "Harrow" },
  { code: "HD", name: "Huddersfield" },
  { code: "HG", name: "Harrogate" },
  { code: "HP", name: "Hemel Hempstead" },
  { code: "HR", name: "Hereford" },
  { code: "HU", name: "Hull" },
  { code: "HX", name: "Halifax" },
  { code: "IG", name: "Ilford" },
  { code: "IP", name: "Ipswich" },
  { code: "IV", name: "Inverness" },
  { code: "KA", name: "Kilmarnock" },
  { code: "KT", name: "Kingston upon Thames" },
  { code: "KY", name: "Kirkcaldy" },
  { code: "L", name: "Liverpool" },
  { code: "LA", name: "Lancaster" },
  { code: "LD", name: "Llandrindod Wells" },
  { code: "LE", name: "Leicester" },
  { code: "LL", name: "Llandudno" },
  { code: "LN", name: "Lincoln" },
  { code: "LS", name: "Leeds" },
  { code: "LU", name: "Luton" },
  { code: "M", name: "Manchester" },
  { code: "ME", name: "Medway" },
  { code: "MK", name: "Milton Keynes" },
  { code: "ML", name: "Motherwell" },
  { code: "N", name: "London N" },
  { code: "NE", name: "Newcastle" },
  { code: "NG", name: "Nottingham" },
  { code: "NN", name: "Northampton" },
  { code: "NP", name: "Newport" },
  { code: "NR", name: "Norwich" },
  { code: "NW", name: "London NW" },
  { code: "OL", name: "Oldham" },
  { code: "OX", name: "Oxford" },
  { code: "PA", name: "Paisley" },
  { code: "PE", name: "Peterborough" },
  { code: "PH", name: "Perth" },
  { code: "PL", name: "Plymouth" },
  { code: "PO", name: "Portsmouth" },
  { code: "PR", name: "Preston" },
  { code: "RG", name: "Reading" },
  { code: "RH", name: "Redhill" },
  { code: "RM", name: "Romford" },
  { code: "S", name: "Sheffield" },
  { code: "SA", name: "Swansea" },
  { code: "SE", name: "London SE" },
  { code: "SG", name: "Stevenage" },
  { code: "SK", name: "Stockport" },
  { code: "SL", name: "Slough" },
  { code: "SM", name: "Sutton" },
  { code: "SN", name: "Swindon" },
  { code: "SO", name: "Southampton" },
  { code: "SP", name: "Salisbury" },
  { code: "SR", name: "Sunderland" },
  { code: "SS", name: "Southend-on-Sea" },
  { code: "ST", name: "Stoke-on-Trent" },
  { code: "SW", name: "London SW" },
  { code: "SY", name: "Shrewsbury" },
  { code: "TA", name: "Taunton" },
  { code: "TD", name: "Galashiels" },
  { code: "TF", name: "Telford" },
  { code: "TN", name: "Tunbridge Wells" },
  { code: "TQ", name: "Torquay" },
  { code: "TR", name: "Truro" },
  { code: "TS", name: "Middlesbrough / Teesside" },
  { code: "TW", name: "Twickenham" },
  { code: "UB", name: "Southall" },
  { code: "W", name: "London W" },
  { code: "WA", name: "Warrington" },
  { code: "WC", name: "London WC" },
  { code: "WD", name: "Watford" },
  { code: "WF", name: "Wakefield" },
  { code: "WN", name: "Wigan" },
  { code: "WR", name: "Worcester" },
  { code: "WS", name: "Walsall" },
  { code: "WV", name: "Wolverhampton" },
  { code: "YO", name: "York" },
];

/** GeoJSON of an area's real postcode districts (same source the map uses). */
export function areaGeojsonUrl(area: string) {
  return `https://raw.githubusercontent.com/missinglink/uk-postcode-polygons/master/geojson/${area}.geojson`;
}
